name: "NEML2 dependencies"
description: "Checkout NEML2 repository, setup Python, CMake, and system dependencies"
inputs:
  path:
    required: false
    default: "."
  ref:
    required: false
    default: ""
  python-version:
    required: true
  cmake-version:
    required: true
  torch-version:
    required: true
  doxygen-version:
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'applied-material-modeling/neml2'
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ inputs.cmake-version }}
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt install lcov mpich
    - name: Install system dependencies (MacOS)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install autoconf automake libtool
        brew install lcov mpich
    - name: Install PyTorch (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        pip install torch==${{ inputs.torch-version }} --index-url https://download.pytorch.org/whl/cpu
    - name: Install PyTorch (MacOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        pip install torch==${{ inputs.torch-version }}
    - name: Install Doxygen (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        DOXYGEN_VERSION="${{ inputs.doxygen-version }}"
        DOXYGEN_RELEASE="${DOXYGEN_VERSION//./_}"
        wget https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_RELEASE}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        tar -xzf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        sudo ln -s doxygen-${DOXYGEN_VERSION}/bin/doxygen /usr/local/bin/doxygen
