name: "NEML2 dependencies"
description: "Checkout NEML2 repository, setup Python, CMake, and system dependencies"
inputs:
  os:
    required: true
  python-version:
    required: true
  cmake-version:
    required: true
  torch-version:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ inputs.cmake-version }}
    - name: Install system dependencies (Ubuntu)
      if: ${{ startsWith(inputs.os, 'ubuntu') }}
      shell: bash
      run: sudo apt install graphviz lcov
    - name: Install system dependencies (MacOS)
      shell: bash
      if: ${{ startsWith(inputs.os, 'macos') }}
      run: brew install graphviz lcov
    - name: Install Python dependencies
      shell: bash
      run: pip install -r requirements.txt
    - name: Install PyTorch CPU-only (Ubuntu)
      shell: bash
      if: ${{ startsWith(inputs.os, 'ubuntu') }}
      run: pip install torch==${{ inputs.torch-version }} --index-url https://download.pytorch.org/whl/cpu
    - name: Install PyTorch CPU-only (MacOS)
      shell: bash
      if: ${{ startsWith(inputs.os, 'macos') }}
      run: pip install torch==${{ inputs.torch-version }}
