name: "NEML2 dependencies"
description: "Checkout NEML2 repository, setup Python, CMake, and system dependencies"
inputs:
  os:
    required: true
  path:
    required: false
    default: "."
  ref:
    required: false
    default: ""
  python-version:
    required: true
  cmake-version:
    required: true
  torch-version:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ inputs.cmake-version }}
    - name: Install system dependencies (Ubuntu)
      if: ${{ startsWith(inputs.os, 'ubuntu') }}
      shell: bash
      run: |
        sudo apt install graphviz lcov
        pip install ninja
        pip install torch==${{ inputs.torch-version }} --index-url https://download.pytorch.org/whl/cpu
    - name: Install system dependencies (MacOS)
      shell: bash
      if: ${{ startsWith(inputs.os, 'macos') }}
      run: |
        brew install graphviz lcov
        pip install ninja
        pip install torch==${{ inputs.torch-version }}
    - name: Install Python dependencies
      shell: bash
      run: cd ${{ inputs.path }} && pip install -r requirements.txt
